INSERT INTO EMPLOYEE VALUES ('1', 'abc', 'engineer', 'abc@wipro.com');  
INSERT INTO EMPLOYEE VALUES ('2', 'KLM', 'ENGINEER', 'KLM@WIPRO.COM');
INSERT INTO EMPLOYEE VALUES ('3', 'XYZ', 'MANAGER', 'XYZ@WIPRO.COM');  